# Generated by Django 4.2.11 on 2024-05-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=128)),
                ('fieldtype', models.CharField(max_length=128)),
                ('projectForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.project')),
            ],
        ),
    ]
