# Generated by Django 4.2.11 on 2024-04-23 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='blogger.form'),
            preserve_default=False,
        ),
    ]
