# Generated by Django 4.2.11 on 2024-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_form_name_alter_formfield_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=128)),
                ('fieldtype', models.CharField(max_length=128)),
            ],
        ),
    ]
