# Generated by Django 4.2.11 on 2024-04-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0007_field_form_delete_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='form',
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ManyToManyField(related_name='fields', to='blogger.form'),
        ),
    ]
