# Generated by Django 4.2.11 on 2024-04-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0008_remove_field_form_field_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='form',
        ),
        migrations.AddField(
            model_name='field',
            name='projectForm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='blogger.form'),
            preserve_default=False,
        ),
    ]
