# Generated by Django 4.2.11 on 2024-04-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0010_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
